pipeline {
  agent none
  
  stages{
    
    stage("build"){
      agent {
        docker{
          image 'maven:3.6.1-jdk-8-slim'
          args '-v $HOME/.m2:/root/.m2'
        }
      }
      when{
         changeset "**/worker/**"
      }
      steps{
        echo 'Compiling worker app'
        dir('worker'){
          sh 'mvn compile'
        }
      }
    }
    
    stage("test"){
      agent {
        docker{
          image 'maven:3.6.1-jdk-8-slim'
        }
      }
      when{
         changeset "**/worker/**"
      }
      steps{
        echo 'Running Unit Test on worker app'
        dir('worker'){
          sh 'mvn clean test'
        }
      }
    }
    
   stage("package"){
      agent any{
      when{
       branch 'master'
         changeset "**/worker/**"
      }
      steps{
        echo 'Packaging worker app'
        dir('worker'){
          sh 'mvn package -DskipTests'
        }
      }
      }    
  }
  
  post{        
      success {
        slackSend (channel: "instavote", message: "ilham - Build Succeeded - Result App - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
      }
      failure {
        slackSend (channel: "instavote", message: "ilham - Build Failed - Result App - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
      }
      always{
        echo 'Building multibranch pipeline for result is completed..'
      }
  }
}

